import { db } from "../../../config/database.js";
import { botFlows } from "../../../infrastructure/database/schema/bot-flows.js";
import { eq } from "drizzle-orm";

const SYSTEM_USER_ID = "00000000-0000-0000-0000-000000000000";

const edgeStyle = { stroke: "#94a3b8", strokeWidth: 2, strokeDasharray: "5 5" };

const templates = [
  {
    name: "Bienvenida Simple",
    description: "Saludo de bienvenida con botones de opciones principales",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "contains_keyword", value: "hola" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 200 },
        data: { message: "Hola 👋 Bienvenido/a a nuestra empresa.\n\nEstamos aqui para ayudarte." },
      },
      {
        id: "buttons-1",
        type: "buttons",
        position: { x: 350, y: 420 },
        data: {
          message: "En que puedo ayudarte hoy?",
          buttons: [
            { emoji: "🛍️", text: "Ver productos" },
            { emoji: "📞", text: "Contactar asesor" },
            { emoji: "🕐", text: "Horarios" },
          ],
        },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "buttons-1", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Captura de Datos",
    description: "Recolecta nombre, email y consulta del cliente paso a paso",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "contains_keyword", value: "info" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 200 },
        data: { question: "Para ayudarte mejor, cual es tu nombre?", variableName: "nombre" },
      },
      {
        id: "ask-2",
        type: "ask",
        position: { x: 350, y: 400 },
        data: { question: "Gracias {{nombre}}! Cual es tu correo electronico?", variableName: "email" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 600 },
        data: { message: "Perfecto {{nombre}}! Un asesor se pondra en contacto contigo a {{email}}. Gracias!" },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "ask-1", target: "ask-2", animated: true, style: edgeStyle },
      { id: "e3-4", source: "ask-2", target: "message-1", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Soporte con IA",
    description: "Usa IA para responder preguntas frecuentes con opcion de transferir a agente",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "any_message" },
      },
      {
        id: "ai-1",
        type: "aiResponse",
        position: { x: 350, y: 200 },
        data: { context: "Eres un asistente de soporte tecnico amable. Responde preguntas sobre nuestros productos y servicios." },
      },
      {
        id: "buttons-1",
        type: "buttons",
        position: { x: 350, y: 450 },
        data: {
          message: "Te fue util mi respuesta?",
          buttons: [
            { emoji: "✅", text: "Si, gracias" },
            { emoji: "👤", text: "Hablar con agente" },
          ],
        },
      },
      {
        id: "transfer-1",
        type: "transferAgent",
        position: { x: 550, y: 650 },
        data: { agentName: "Soporte", message: "Te transfiero con un agente humano. Un momento por favor..." },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "ai-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "ai-1", target: "buttons-1", animated: true, style: edgeStyle },
      { id: "e3-4", source: "buttons-1", sourceHandle: "btn-1", target: "transfer-1", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Menu de Opciones",
    description: "Menu principal con condiciones para redirigir segun la seleccion",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "first_message" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 180 },
        data: { message: "Bienvenido! 🎉\n\nEscribe el numero de la opcion:\n1️⃣ Productos\n2️⃣ Precios\n3️⃣ Soporte\n4️⃣ Ubicacion" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 400 },
        data: { question: "Selecciona una opcion (1-4):", variableName: "opcion" },
      },
      {
        id: "condition-1",
        type: "condition",
        position: { x: 350, y: 600 },
        data: { variable: "opcion", operator: "equals", value: "1" },
      },
      {
        id: "message-2",
        type: "message",
        position: { x: 150, y: 800 },
        data: { message: "Nuestros productos:\n📱 Producto A - $50\n💻 Producto B - $100\n🎧 Producto C - $30" },
      },
      {
        id: "message-3",
        type: "message",
        position: { x: 550, y: 800 },
        data: { message: "Para esa opcion, escribe 'soporte' para hablar con un asesor." },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e3-4", source: "ask-1", target: "condition-1", animated: true, style: edgeStyle },
      { id: "e4-5", source: "condition-1", sourceHandle: "yes", target: "message-2", animated: true, style: edgeStyle },
      { id: "e4-6", source: "condition-1", sourceHandle: "no", target: "message-3", animated: true, style: edgeStyle },
    ],
  },
  // ========== NUEVAS PLANTILLAS ==========
  {
    name: "Tienda Online",
    description: "Bot completo para e-commerce: catalogo, pedidos, seguimiento y pagos",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "first_message" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 200 },
        data: { message: "🛒 Bienvenido a nuestra Tienda Online!\n\nTenemos las mejores ofertas para ti.\nEscribe una opcion:\n\n1️⃣ Ver Catalogo\n2️⃣ Hacer un Pedido\n3️⃣ Rastrear mi Pedido\n4️⃣ Metodos de Pago\n5️⃣ Hablar con Ventas" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 450 },
        data: { question: "Escribe el numero de tu opcion:", variableName: "opcion" },
      },
      {
        id: "condition-cat",
        type: "condition",
        position: { x: 100, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "1" },
      },
      {
        id: "message-cat",
        type: "message",
        position: { x: -100, y: 850 },
        data: { message: "📦 Nuestro Catalogo:\n\n🔥 *Ofertas de la semana:*\n• Camiseta Premium - $25.000\n• Zapatillas Running - $89.000\n• Reloj Smart - $150.000\n• Audifonos BT - $45.000\n\n📸 Envia 'fotos' para ver imagenes\n🛒 Envia el nombre del producto para agregarlo al carrito" },
      },
      {
        id: "condition-ped",
        type: "condition",
        position: { x: 350, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "2" },
      },
      {
        id: "ask-prod",
        type: "ask",
        position: { x: 350, y: 870 },
        data: { question: "Que producto deseas pedir?", variableName: "producto" },
      },
      {
        id: "ask-cant",
        type: "ask",
        position: { x: 350, y: 1050 },
        data: { question: "Cuantas unidades de {{producto}}?", variableName: "cantidad" },
      },
      {
        id: "ask-dir",
        type: "ask",
        position: { x: 350, y: 1230 },
        data: { question: "Cual es tu direccion de envio?", variableName: "direccion" },
      },
      {
        id: "message-confirm",
        type: "message",
        position: { x: 350, y: 1410 },
        data: { message: "✅ *Resumen de tu pedido:*\n\n📦 Producto: {{producto}}\n📊 Cantidad: {{cantidad}}\n📍 Direccion: {{direccion}}\n\nUn asesor confirmara tu pedido y te enviara el link de pago. Gracias! 🙏" },
      },
      {
        id: "condition-track",
        type: "condition",
        position: { x: 600, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "3" },
      },
      {
        id: "ask-track",
        type: "ask",
        position: { x: 600, y: 850 },
        data: { question: "Ingresa tu numero de pedido:", variableName: "num_pedido" },
      },
      {
        id: "message-track",
        type: "message",
        position: { x: 600, y: 1050 },
        data: { message: "🔍 Buscando pedido #{{num_pedido}}...\n\nUn asesor te enviara el estado actualizado de tu pedido en breve. Gracias por tu paciencia!" },
      },
      {
        id: "condition-pay",
        type: "condition",
        position: { x: 850, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "4" },
      },
      {
        id: "message-pay",
        type: "message",
        position: { x: 850, y: 850 },
        data: { message: "💳 *Metodos de Pago:*\n\n🏦 Transferencia Bancaria\n   Banco: Bancolombia\n   Cuenta: 123-456789-00\n   Titular: Mi Empresa SAS\n\n💰 Nequi/Daviplata: 300-123-4567\n\n💳 Link de pago (te lo enviamos al confirmar pedido)\n\n📸 Envia tu comprobante de pago aqui" },
      },
      {
        id: "transfer-ventas",
        type: "transferAgent",
        position: { x: 1100, y: 650 },
        data: { agentName: "Ventas", message: "👤 Te conecto con nuestro equipo de ventas. Un momento..." },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e3-cat", source: "ask-1", target: "condition-cat", animated: true, style: edgeStyle },
      { id: "ecat-y", source: "condition-cat", sourceHandle: "yes", target: "message-cat", animated: true, style: edgeStyle },
      { id: "ecat-n", source: "condition-cat", sourceHandle: "no", target: "condition-ped", animated: true, style: edgeStyle },
      { id: "eped-y", source: "condition-ped", sourceHandle: "yes", target: "ask-prod", animated: true, style: edgeStyle },
      { id: "eped-n", source: "condition-ped", sourceHandle: "no", target: "condition-track", animated: true, style: edgeStyle },
      { id: "eprod-cant", source: "ask-prod", target: "ask-cant", animated: true, style: edgeStyle },
      { id: "ecant-dir", source: "ask-cant", target: "ask-dir", animated: true, style: edgeStyle },
      { id: "edir-conf", source: "ask-dir", target: "message-confirm", animated: true, style: edgeStyle },
      { id: "etrack-y", source: "condition-track", sourceHandle: "yes", target: "ask-track", animated: true, style: edgeStyle },
      { id: "etrack-n", source: "condition-track", sourceHandle: "no", target: "condition-pay", animated: true, style: edgeStyle },
      { id: "etrack-msg", source: "ask-track", target: "message-track", animated: true, style: edgeStyle },
      { id: "epay-y", source: "condition-pay", sourceHandle: "yes", target: "message-pay", animated: true, style: edgeStyle },
      { id: "epay-n", source: "condition-pay", sourceHandle: "no", target: "transfer-ventas", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Restaurante / Pedidos de Comida",
    description: "Bot para restaurantes: menu, pedidos a domicilio, reservas y horarios",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "first_message" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 200 },
        data: { message: "🍽️ *Bienvenido a Restaurante Delicia!*\n\nQue deseas hacer?\n\n1️⃣ Ver Menu del Dia\n2️⃣ Pedir a Domicilio\n3️⃣ Reservar Mesa\n4️⃣ Horarios y Ubicacion\n5️⃣ Hablar con nosotros" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 450 },
        data: { question: "Escribe tu opcion:", variableName: "opcion" },
      },
      {
        id: "condition-menu",
        type: "condition",
        position: { x: 50, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "1" },
      },
      {
        id: "message-menu",
        type: "message",
        position: { x: -150, y: 850 },
        data: { message: "📋 *Menu del Dia:*\n\n🥗 *Entradas:*\n• Ensalada Cesar - $12.000\n• Sopa del Dia - $8.000\n• Empanadas x3 - $10.000\n\n🥩 *Platos Fuertes:*\n• Bandeja Paisa - $22.000\n• Pollo a la Plancha - $18.000\n• Salmon Grille - $28.000\n• Pasta Alfredo - $16.000\n\n🍰 *Postres:*\n• Tres Leches - $8.000\n• Brownie con Helado - $10.000\n\n🥤 *Bebidas:*\n• Jugo Natural - $5.000\n• Gaseosa - $3.000\n• Limonada - $4.000\n\nPara pedir escribe *2*" },
      },
      {
        id: "condition-pedir",
        type: "condition",
        position: { x: 300, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "2" },
      },
      {
        id: "ask-pedido",
        type: "ask",
        position: { x: 300, y: 870 },
        data: { question: "Que deseas pedir? (puedes escribir varios platos)", variableName: "pedido" },
      },
      {
        id: "ask-nombre",
        type: "ask",
        position: { x: 300, y: 1050 },
        data: { question: "A nombre de quien es el pedido?", variableName: "nombre" },
      },
      {
        id: "ask-direccion",
        type: "ask",
        position: { x: 300, y: 1230 },
        data: { question: "Direccion de entrega:", variableName: "direccion" },
      },
      {
        id: "ask-tel",
        type: "ask",
        position: { x: 300, y: 1410 },
        data: { question: "Telefono de contacto:", variableName: "telefono" },
      },
      {
        id: "message-pedido-conf",
        type: "message",
        position: { x: 300, y: 1590 },
        data: { message: "✅ *Pedido registrado!*\n\n👤 {{nombre}}\n🍽️ {{pedido}}\n📍 {{direccion}}\n📱 {{telefono}}\n\n⏰ Tiempo estimado: 30-45 min\n💰 Te confirmaremos el total por aqui.\n\nGracias por tu pedido! 🙏" },
      },
      {
        id: "condition-reserva",
        type: "condition",
        position: { x: 550, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "3" },
      },
      {
        id: "ask-fecha",
        type: "ask",
        position: { x: 550, y: 870 },
        data: { question: "Para que fecha deseas la reserva? (ej: 15 de marzo)", variableName: "fecha" },
      },
      {
        id: "ask-hora",
        type: "ask",
        position: { x: 550, y: 1050 },
        data: { question: "A que hora? (ej: 7:00 PM)", variableName: "hora" },
      },
      {
        id: "ask-personas",
        type: "ask",
        position: { x: 550, y: 1230 },
        data: { question: "Para cuantas personas?", variableName: "personas" },
      },
      {
        id: "ask-nombre-res",
        type: "ask",
        position: { x: 550, y: 1410 },
        data: { question: "A nombre de quien la reserva?", variableName: "nombre_reserva" },
      },
      {
        id: "message-reserva-conf",
        type: "message",
        position: { x: 550, y: 1590 },
        data: { message: "🎉 *Reserva registrada!*\n\n👤 {{nombre_reserva}}\n📅 {{fecha}}\n🕐 {{hora}}\n👥 {{personas}} personas\n\nTe esperamos! Si necesitas cancelar, escribenos con anticipacion." },
      },
      {
        id: "condition-info",
        type: "condition",
        position: { x: 800, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "4" },
      },
      {
        id: "message-info",
        type: "message",
        position: { x: 800, y: 850 },
        data: { message: "📍 *Ubicacion:*\nCalle 123 #45-67, Centro Comercial Plaza\n\n🕐 *Horarios:*\nLunes a Viernes: 11:00 AM - 10:00 PM\nSabados: 11:00 AM - 11:00 PM\nDomingos: 12:00 PM - 9:00 PM\n\n📱 Telefono: (601) 234-5678\n🌐 www.restaurantedelicia.com\n\n🅿️ Parqueadero gratuito" },
      },
      {
        id: "transfer-1",
        type: "transferAgent",
        position: { x: 1050, y: 650 },
        data: { agentName: "Restaurante", message: "👨‍🍳 Te conecto con nuestro equipo. Un momento..." },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e3-menu", source: "ask-1", target: "condition-menu", animated: true, style: edgeStyle },
      { id: "emenu-y", source: "condition-menu", sourceHandle: "yes", target: "message-menu", animated: true, style: edgeStyle },
      { id: "emenu-n", source: "condition-menu", sourceHandle: "no", target: "condition-pedir", animated: true, style: edgeStyle },
      { id: "epedir-y", source: "condition-pedir", sourceHandle: "yes", target: "ask-pedido", animated: true, style: edgeStyle },
      { id: "epedir-n", source: "condition-pedir", sourceHandle: "no", target: "condition-reserva", animated: true, style: edgeStyle },
      { id: "eped-nom", source: "ask-pedido", target: "ask-nombre", animated: true, style: edgeStyle },
      { id: "enom-dir", source: "ask-nombre", target: "ask-direccion", animated: true, style: edgeStyle },
      { id: "edir-tel", source: "ask-direccion", target: "ask-tel", animated: true, style: edgeStyle },
      { id: "etel-conf", source: "ask-tel", target: "message-pedido-conf", animated: true, style: edgeStyle },
      { id: "eres-y", source: "condition-reserva", sourceHandle: "yes", target: "ask-fecha", animated: true, style: edgeStyle },
      { id: "eres-n", source: "condition-reserva", sourceHandle: "no", target: "condition-info", animated: true, style: edgeStyle },
      { id: "efecha-hora", source: "ask-fecha", target: "ask-hora", animated: true, style: edgeStyle },
      { id: "ehora-per", source: "ask-hora", target: "ask-personas", animated: true, style: edgeStyle },
      { id: "eper-nom", source: "ask-personas", target: "ask-nombre-res", animated: true, style: edgeStyle },
      { id: "enom-conf", source: "ask-nombre-res", target: "message-reserva-conf", animated: true, style: edgeStyle },
      { id: "einfo-y", source: "condition-info", sourceHandle: "yes", target: "message-info", animated: true, style: edgeStyle },
      { id: "einfo-n", source: "condition-info", sourceHandle: "no", target: "transfer-1", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Agencia de Viajes",
    description: "Bot para agencias: destinos, cotizaciones, paquetes y reservas",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "first_message" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 200 },
        data: { message: "✈️ *Bienvenido a Viajes Express!*\n\nSomos tu mejor opcion para viajar.\n\n1️⃣ Destinos Disponibles\n2️⃣ Cotizar un Viaje\n3️⃣ Paquetes Todo Incluido\n4️⃣ Estado de mi Reserva\n5️⃣ Hablar con Asesor" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 450 },
        data: { question: "Que te interesa?", variableName: "opcion" },
      },
      {
        id: "condition-dest",
        type: "condition",
        position: { x: 50, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "1" },
      },
      {
        id: "message-dest",
        type: "message",
        position: { x: -150, y: 850 },
        data: { message: "🌎 *Destinos Populares:*\n\n🏖️ *Playa:*\n• Cancun - desde $1.200.000\n• San Andres - desde $800.000\n• Cartagena - desde $600.000\n• Punta Cana - desde $2.500.000\n\n🏔️ *Aventura:*\n• Eje Cafetero - desde $500.000\n• Santa Marta - desde $700.000\n• Villa de Leyva - desde $400.000\n\n🌍 *Internacional:*\n• Miami - desde $3.000.000\n• Madrid - desde $4.500.000\n• Buenos Aires - desde $2.800.000\n\nEscribe *2* para cotizar!" },
      },
      {
        id: "condition-cotizar",
        type: "condition",
        position: { x: 300, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "2" },
      },
      {
        id: "ask-destino",
        type: "ask",
        position: { x: 300, y: 870 },
        data: { question: "A donde quieres viajar?", variableName: "destino" },
      },
      {
        id: "ask-fechas",
        type: "ask",
        position: { x: 300, y: 1050 },
        data: { question: "Fechas de viaje? (ej: 15 al 20 de abril)", variableName: "fechas" },
      },
      {
        id: "ask-viajeros",
        type: "ask",
        position: { x: 300, y: 1230 },
        data: { question: "Cuantas personas viajan? (adultos y ninos)", variableName: "viajeros" },
      },
      {
        id: "ask-presupuesto",
        type: "ask",
        position: { x: 300, y: 1410 },
        data: { question: "Cual es tu presupuesto aproximado por persona?", variableName: "presupuesto" },
      },
      {
        id: "ask-contacto",
        type: "ask",
        position: { x: 300, y: 1590 },
        data: { question: "Tu nombre y telefono para enviarte la cotizacion:", variableName: "contacto" },
      },
      {
        id: "message-cotizar-conf",
        type: "message",
        position: { x: 300, y: 1770 },
        data: { message: "✅ *Solicitud de Cotizacion:*\n\n🌍 {{destino}}\n📅 {{fechas}}\n👥 {{viajeros}}\n💰 {{presupuesto}}\n👤 {{contacto}}\n\nNuestro asesor te enviara la cotizacion en maximo 2 horas. Gracias! ✈️" },
      },
      {
        id: "condition-paq",
        type: "condition",
        position: { x: 550, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "3" },
      },
      {
        id: "message-paq",
        type: "message",
        position: { x: 550, y: 850 },
        data: { message: "🎁 *Paquetes Todo Incluido:*\n\n🌴 *Cancun 5D/4N* - $2.800.000/persona\n✅ Vuelo + Hotel 5⭐ + Alimentacion\n\n🏝️ *San Andres 4D/3N* - $1.500.000/persona\n✅ Vuelo + Hotel + Tours\n\n🏖️ *Punta Cana 6D/5N* - $4.200.000/persona\n✅ Vuelo + Resort AI + Traslados\n\n🗽 *Miami 5D/4N* - $5.500.000/persona\n✅ Vuelo + Hotel + Parques\n\nEscribe *2* para cotizar cualquier paquete!" },
      },
      {
        id: "transfer-asesor",
        type: "transferAgent",
        position: { x: 800, y: 650 },
        data: { agentName: "Asesor de Viajes", message: "👋 Te conecto con un asesor especializado. Un momento..." },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e3-dest", source: "ask-1", target: "condition-dest", animated: true, style: edgeStyle },
      { id: "edest-y", source: "condition-dest", sourceHandle: "yes", target: "message-dest", animated: true, style: edgeStyle },
      { id: "edest-n", source: "condition-dest", sourceHandle: "no", target: "condition-cotizar", animated: true, style: edgeStyle },
      { id: "ecot-y", source: "condition-cotizar", sourceHandle: "yes", target: "ask-destino", animated: true, style: edgeStyle },
      { id: "ecot-n", source: "condition-cotizar", sourceHandle: "no", target: "condition-paq", animated: true, style: edgeStyle },
      { id: "edest-fecha", source: "ask-destino", target: "ask-fechas", animated: true, style: edgeStyle },
      { id: "efecha-viaj", source: "ask-fechas", target: "ask-viajeros", animated: true, style: edgeStyle },
      { id: "eviaj-pres", source: "ask-viajeros", target: "ask-presupuesto", animated: true, style: edgeStyle },
      { id: "epres-cont", source: "ask-presupuesto", target: "ask-contacto", animated: true, style: edgeStyle },
      { id: "econt-conf", source: "ask-contacto", target: "message-cotizar-conf", animated: true, style: edgeStyle },
      { id: "epaq-y", source: "condition-paq", sourceHandle: "yes", target: "message-paq", animated: true, style: edgeStyle },
      { id: "epaq-n", source: "condition-paq", sourceHandle: "no", target: "transfer-asesor", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Clinica / Consultorio Medico",
    description: "Bot para salud: agendar citas, especialidades, ubicacion y urgencias",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "first_message" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 200 },
        data: { message: "🏥 *Clinica Salud Total*\n\nBienvenido! Como podemos ayudarte?\n\n1️⃣ Agendar Cita\n2️⃣ Nuestras Especialidades\n3️⃣ Resultados de Examenes\n4️⃣ Horarios y Ubicacion\n5️⃣ Urgencias" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 450 },
        data: { question: "Selecciona una opcion:", variableName: "opcion" },
      },
      {
        id: "condition-cita",
        type: "condition",
        position: { x: 50, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "1" },
      },
      {
        id: "ask-espec",
        type: "ask",
        position: { x: -100, y: 870 },
        data: { question: "Con que especialidad deseas tu cita?\n\n• Medicina General\n• Odontologia\n• Pediatria\n• Ginecologia\n• Dermatologia\n• Oftalmologia", variableName: "especialidad" },
      },
      {
        id: "ask-paciente",
        type: "ask",
        position: { x: -100, y: 1080 },
        data: { question: "Nombre completo del paciente:", variableName: "paciente" },
      },
      {
        id: "ask-cedula",
        type: "ask",
        position: { x: -100, y: 1260 },
        data: { question: "Numero de cedula:", variableName: "cedula" },
      },
      {
        id: "ask-tel-cita",
        type: "ask",
        position: { x: -100, y: 1440 },
        data: { question: "Telefono de contacto:", variableName: "telefono" },
      },
      {
        id: "ask-preferencia",
        type: "ask",
        position: { x: -100, y: 1620 },
        data: { question: "Prefieres cita en la manana o en la tarde?", variableName: "preferencia" },
      },
      {
        id: "message-cita-conf",
        type: "message",
        position: { x: -100, y: 1800 },
        data: { message: "✅ *Solicitud de Cita Registrada:*\n\n👤 {{paciente}}\n🆔 CC: {{cedula}}\n🩺 {{especialidad}}\n📱 {{telefono}}\n🕐 Preferencia: {{preferencia}}\n\nLe confirmaremos fecha y hora disponible en las proximas horas. Gracias!" },
      },
      {
        id: "condition-esp",
        type: "condition",
        position: { x: 300, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "2" },
      },
      {
        id: "message-esp",
        type: "message",
        position: { x: 300, y: 870 },
        data: { message: "🩺 *Nuestras Especialidades:*\n\n👨‍⚕️ Medicina General\n🦷 Odontologia\n👶 Pediatria\n👩‍⚕️ Ginecologia\n🔬 Dermatologia\n👁️ Oftalmologia\n❤️ Cardiologia\n🦴 Ortopedia\n🧠 Neurologia\n🧪 Laboratorio Clinico\n📷 Imagenes Diagnosticas\n\nEscribe *1* para agendar tu cita!" },
      },
      {
        id: "condition-exam",
        type: "condition",
        position: { x: 550, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "3" },
      },
      {
        id: "ask-cedula-exam",
        type: "ask",
        position: { x: 550, y: 870 },
        data: { question: "Ingresa tu numero de cedula para buscar tus resultados:", variableName: "cedula_exam" },
      },
      {
        id: "message-exam",
        type: "message",
        position: { x: 550, y: 1080 },
        data: { message: "🔍 Buscando resultados para CC: {{cedula_exam}}...\n\nUn asistente te enviara los resultados disponibles. Por seguridad, algunos resultados solo se entregan presencialmente." },
      },
      {
        id: "condition-horario",
        type: "condition",
        position: { x: 800, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "4" },
      },
      {
        id: "message-horario",
        type: "message",
        position: { x: 800, y: 870 },
        data: { message: "📍 *Ubicacion:*\nAv. Principal #12-34, Centro Medico\n\n🕐 *Horarios:*\nLunes a Viernes: 6:00 AM - 8:00 PM\nSabados: 7:00 AM - 2:00 PM\nDomingos: Cerrado\n\n🚨 *Urgencias:* 24 horas\n📞 Telefono: (601) 987-6543\n\n🅿️ Parqueadero disponible" },
      },
      {
        id: "message-urgencia",
        type: "message",
        position: { x: 1050, y: 650 },
        data: { message: "🚨 *URGENCIAS*\n\nSi tienes una emergencia medica:\n\n📞 Llama al: (601) 987-6543 ext. 100\n🏥 Urgencias 24 horas\n📍 Av. Principal #12-34\n\n⚠️ Si es una emergencia vital, llama al *123* inmediatamente." },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e3-cita", source: "ask-1", target: "condition-cita", animated: true, style: edgeStyle },
      { id: "ecita-y", source: "condition-cita", sourceHandle: "yes", target: "ask-espec", animated: true, style: edgeStyle },
      { id: "ecita-n", source: "condition-cita", sourceHandle: "no", target: "condition-esp", animated: true, style: edgeStyle },
      { id: "eespec-pac", source: "ask-espec", target: "ask-paciente", animated: true, style: edgeStyle },
      { id: "epac-ced", source: "ask-paciente", target: "ask-cedula", animated: true, style: edgeStyle },
      { id: "eced-tel", source: "ask-cedula", target: "ask-tel-cita", animated: true, style: edgeStyle },
      { id: "etel-pref", source: "ask-tel-cita", target: "ask-preferencia", animated: true, style: edgeStyle },
      { id: "epref-conf", source: "ask-preferencia", target: "message-cita-conf", animated: true, style: edgeStyle },
      { id: "eesp-y", source: "condition-esp", sourceHandle: "yes", target: "message-esp", animated: true, style: edgeStyle },
      { id: "eesp-n", source: "condition-esp", sourceHandle: "no", target: "condition-exam", animated: true, style: edgeStyle },
      { id: "eexam-y", source: "condition-exam", sourceHandle: "yes", target: "ask-cedula-exam", animated: true, style: edgeStyle },
      { id: "eexam-n", source: "condition-exam", sourceHandle: "no", target: "condition-horario", animated: true, style: edgeStyle },
      { id: "eced-exam", source: "ask-cedula-exam", target: "message-exam", animated: true, style: edgeStyle },
      { id: "ehor-y", source: "condition-horario", sourceHandle: "yes", target: "message-horario", animated: true, style: edgeStyle },
      { id: "ehor-n", source: "condition-horario", sourceHandle: "no", target: "message-urgencia", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Inmobiliaria",
    description: "Bot para inmobiliarias: busqueda de propiedades, agendar visitas y cotizaciones",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "first_message" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 200 },
        data: { message: "🏠 *Inmobiliaria Tu Hogar*\n\nEncuentra la propiedad de tus sueños!\n\n1️⃣ Buscar Propiedades\n2️⃣ Agendar Visita\n3️⃣ Vender/Arrendar mi Propiedad\n4️⃣ Simular Credito\n5️⃣ Hablar con Asesor" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 450 },
        data: { question: "Que te interesa?", variableName: "opcion" },
      },
      {
        id: "condition-buscar",
        type: "condition",
        position: { x: 50, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "1" },
      },
      {
        id: "ask-tipo",
        type: "ask",
        position: { x: -100, y: 870 },
        data: { question: "Que buscas?\n\n• Apartamento\n• Casa\n• Local Comercial\n• Oficina\n• Lote", variableName: "tipo" },
      },
      {
        id: "ask-zona",
        type: "ask",
        position: { x: -100, y: 1080 },
        data: { question: "En que zona o barrio?", variableName: "zona" },
      },
      {
        id: "ask-presupuesto-inm",
        type: "ask",
        position: { x: -100, y: 1260 },
        data: { question: "Presupuesto maximo? (ej: $200.000.000 o arriendo $1.500.000)", variableName: "presupuesto" },
      },
      {
        id: "ask-hab",
        type: "ask",
        position: { x: -100, y: 1440 },
        data: { question: "Cuantas habitaciones necesitas?", variableName: "habitaciones" },
      },
      {
        id: "message-buscar-conf",
        type: "message",
        position: { x: -100, y: 1620 },
        data: { message: "🔍 *Busqueda registrada:*\n\n🏠 {{tipo}}\n📍 {{zona}}\n💰 {{presupuesto}}\n🛏️ {{habitaciones}} habitaciones\n\nTe enviaremos opciones disponibles que coincidan. Un asesor se pondra en contacto contigo!" },
      },
      {
        id: "condition-visita",
        type: "condition",
        position: { x: 350, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "2" },
      },
      {
        id: "ask-codigo",
        type: "ask",
        position: { x: 350, y: 870 },
        data: { question: "Tienes el codigo de la propiedad? (si no, describe cual te interesa)", variableName: "codigo_prop" },
      },
      {
        id: "ask-nombre-vis",
        type: "ask",
        position: { x: 350, y: 1080 },
        data: { question: "Tu nombre completo:", variableName: "nombre" },
      },
      {
        id: "ask-tel-vis",
        type: "ask",
        position: { x: 350, y: 1260 },
        data: { question: "Tu telefono:", variableName: "telefono" },
      },
      {
        id: "ask-dia-vis",
        type: "ask",
        position: { x: 350, y: 1440 },
        data: { question: "Que dia te gustaria la visita?", variableName: "dia_visita" },
      },
      {
        id: "message-visita-conf",
        type: "message",
        position: { x: 350, y: 1620 },
        data: { message: "📋 *Visita Agendada:*\n\n🏠 Propiedad: {{codigo_prop}}\n👤 {{nombre}}\n📱 {{telefono}}\n📅 {{dia_visita}}\n\nUn asesor confirmara la hora exacta. Gracias!" },
      },
      {
        id: "condition-vender",
        type: "condition",
        position: { x: 650, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "3" },
      },
      {
        id: "ask-tipo-venta",
        type: "ask",
        position: { x: 650, y: 870 },
        data: { question: "Deseas *vender* o *arrendar* tu propiedad?", variableName: "tipo_operacion" },
      },
      {
        id: "ask-desc-prop",
        type: "ask",
        position: { x: 650, y: 1080 },
        data: { question: "Describenos tu propiedad (tipo, ubicacion, metros, habitaciones, precio esperado):", variableName: "descripcion_prop" },
      },
      {
        id: "message-vender-conf",
        type: "message",
        position: { x: 650, y: 1260 },
        data: { message: "✅ *Solicitud recibida!*\n\n📋 {{tipo_operacion}}\n🏠 {{descripcion_prop}}\n\nUn asesor te contactara para evaluar tu propiedad y darte una valoracion. Tambien puedes enviarnos fotos por aqui!" },
      },
      {
        id: "transfer-asesor",
        type: "transferAgent",
        position: { x: 950, y: 650 },
        data: { agentName: "Asesor Inmobiliario", message: "🏠 Te conecto con un asesor inmobiliario. Un momento..." },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e3-bus", source: "ask-1", target: "condition-buscar", animated: true, style: edgeStyle },
      { id: "ebus-y", source: "condition-buscar", sourceHandle: "yes", target: "ask-tipo", animated: true, style: edgeStyle },
      { id: "ebus-n", source: "condition-buscar", sourceHandle: "no", target: "condition-visita", animated: true, style: edgeStyle },
      { id: "etipo-zona", source: "ask-tipo", target: "ask-zona", animated: true, style: edgeStyle },
      { id: "ezona-pres", source: "ask-zona", target: "ask-presupuesto-inm", animated: true, style: edgeStyle },
      { id: "epres-hab", source: "ask-presupuesto-inm", target: "ask-hab", animated: true, style: edgeStyle },
      { id: "ehab-conf", source: "ask-hab", target: "message-buscar-conf", animated: true, style: edgeStyle },
      { id: "evis-y", source: "condition-visita", sourceHandle: "yes", target: "ask-codigo", animated: true, style: edgeStyle },
      { id: "evis-n", source: "condition-visita", sourceHandle: "no", target: "condition-vender", animated: true, style: edgeStyle },
      { id: "ecod-nom", source: "ask-codigo", target: "ask-nombre-vis", animated: true, style: edgeStyle },
      { id: "enom-tel", source: "ask-nombre-vis", target: "ask-tel-vis", animated: true, style: edgeStyle },
      { id: "etel-dia", source: "ask-tel-vis", target: "ask-dia-vis", animated: true, style: edgeStyle },
      { id: "edia-conf", source: "ask-dia-vis", target: "message-visita-conf", animated: true, style: edgeStyle },
      { id: "even-y", source: "condition-vender", sourceHandle: "yes", target: "ask-tipo-venta", animated: true, style: edgeStyle },
      { id: "even-n", source: "condition-vender", sourceHandle: "no", target: "transfer-asesor", animated: true, style: edgeStyle },
      { id: "etv-desc", source: "ask-tipo-venta", target: "ask-desc-prop", animated: true, style: edgeStyle },
      { id: "edesc-conf", source: "ask-desc-prop", target: "message-vender-conf", animated: true, style: edgeStyle },
    ],
  },
  {
    name: "Gimnasio / Centro Fitness",
    description: "Bot para gimnasios: planes, horarios, inscripcion y clases",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 400, y: 50 },
        data: { triggerType: "first_message" },
      },
      {
        id: "message-1",
        type: "message",
        position: { x: 350, y: 200 },
        data: { message: "💪 *Gym Power Fitness*\n\nTransforma tu cuerpo, transforma tu vida!\n\n1️⃣ Planes y Precios\n2️⃣ Horarios de Clases\n3️⃣ Inscribirme\n4️⃣ Congelar/Cancelar Membresia\n5️⃣ Ubicacion y Contacto" },
      },
      {
        id: "ask-1",
        type: "ask",
        position: { x: 350, y: 450 },
        data: { question: "Que te interesa?", variableName: "opcion" },
      },
      {
        id: "condition-planes",
        type: "condition",
        position: { x: 50, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "1" },
      },
      {
        id: "message-planes",
        type: "message",
        position: { x: -150, y: 870 },
        data: { message: "🏋️ *Nuestros Planes:*\n\n🥉 *Plan Basico* - $80.000/mes\n• Acceso a maquinas y cardio\n• Lun a Vie 6AM-10PM\n\n🥈 *Plan Full* - $120.000/mes\n• Todo el Plan Basico +\n• Clases grupales ilimitadas\n• Sabados incluidos\n\n🥇 *Plan Premium* - $180.000/mes\n• Todo el Plan Full +\n• Entrenador personal 2x/semana\n• Nutricionista 1x/mes\n• Acceso 7 dias\n\n🎁 *Promocion:* Inscripcion GRATIS este mes!\n\nEscribe *3* para inscribirte!" },
      },
      {
        id: "condition-clases",
        type: "condition",
        position: { x: 300, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "2" },
      },
      {
        id: "message-clases",
        type: "message",
        position: { x: 300, y: 870 },
        data: { message: "📅 *Horarios de Clases:*\n\n🌅 *Manana:*\n6:00 AM - Spinning\n7:00 AM - Yoga\n8:00 AM - Funcional\n9:00 AM - Pilates\n\n🌞 *Medio Dia:*\n12:00 PM - Express Cardio\n1:00 PM - TRX\n\n🌙 *Noche:*\n5:00 PM - Zumba\n6:00 PM - CrossFit\n7:00 PM - Boxeo\n8:00 PM - Stretching\n\n📌 Clases disponibles con Plan Full y Premium\nEscribe *3* para inscribirte!" },
      },
      {
        id: "condition-inscripcion",
        type: "condition",
        position: { x: 550, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "3" },
      },
      {
        id: "ask-nombre-gym",
        type: "ask",
        position: { x: 550, y: 870 },
        data: { question: "Nombre completo:", variableName: "nombre" },
      },
      {
        id: "ask-tel-gym",
        type: "ask",
        position: { x: 550, y: 1050 },
        data: { question: "Telefono:", variableName: "telefono" },
      },
      {
        id: "ask-plan",
        type: "ask",
        position: { x: 550, y: 1230 },
        data: { question: "Que plan te interesa? (Basico, Full o Premium)", variableName: "plan" },
      },
      {
        id: "ask-inicio",
        type: "ask",
        position: { x: 550, y: 1410 },
        data: { question: "Cuando deseas iniciar?", variableName: "inicio" },
      },
      {
        id: "message-insc-conf",
        type: "message",
        position: { x: 550, y: 1590 },
        data: { message: "🎉 *Pre-inscripcion Exitosa!*\n\n👤 {{nombre}}\n📱 {{telefono}}\n💎 Plan: {{plan}}\n📅 Inicio: {{inicio}}\n\nPresentate en recepcion con tu cedula para completar la inscripcion.\n🎁 Recuerda: Inscripcion GRATIS este mes!\n\nTe esperamos! 💪" },
      },
      {
        id: "condition-congelar",
        type: "condition",
        position: { x: 800, y: 650 },
        data: { variable: "opcion", operator: "equals", value: "4" },
      },
      {
        id: "message-congelar",
        type: "message",
        position: { x: 800, y: 870 },
        data: { message: "❄️ *Congelar/Cancelar Membresia:*\n\n• Congelamiento: maximo 30 dias por semestre\n• Cancelacion: con 15 dias de anticipacion\n\nPara cualquiera de las dos, acercate a recepcion con tu cedula o escribe *5* para hablar con nosotros." },
      },
      {
        id: "message-ubicacion",
        type: "message",
        position: { x: 1050, y: 650 },
        data: { message: "📍 *Ubicacion:*\nCentro Comercial Fitness, Local 201\nAv. Deportiva #100-50\n\n🕐 *Horarios:*\nLun-Vie: 5:00 AM - 10:00 PM\nSab: 6:00 AM - 2:00 PM\nDom: 7:00 AM - 12:00 PM\n\n📱 (601) 555-GYM1\n📧 info@gympowerfitness.com\n🌐 www.gympowerfitness.com" },
      },
    ],
    edges: [
      { id: "e1-2", source: "trigger-1", target: "message-1", animated: true, style: edgeStyle },
      { id: "e2-3", source: "message-1", target: "ask-1", animated: true, style: edgeStyle },
      { id: "e3-planes", source: "ask-1", target: "condition-planes", animated: true, style: edgeStyle },
      { id: "eplan-y", source: "condition-planes", sourceHandle: "yes", target: "message-planes", animated: true, style: edgeStyle },
      { id: "eplan-n", source: "condition-planes", sourceHandle: "no", target: "condition-clases", animated: true, style: edgeStyle },
      { id: "eclas-y", source: "condition-clases", sourceHandle: "yes", target: "message-clases", animated: true, style: edgeStyle },
      { id: "eclas-n", source: "condition-clases", sourceHandle: "no", target: "condition-inscripcion", animated: true, style: edgeStyle },
      { id: "einsc-y", source: "condition-inscripcion", sourceHandle: "yes", target: "ask-nombre-gym", animated: true, style: edgeStyle },
      { id: "einsc-n", source: "condition-inscripcion", sourceHandle: "no", target: "condition-congelar", animated: true, style: edgeStyle },
      { id: "enom-tel", source: "ask-nombre-gym", target: "ask-tel-gym", animated: true, style: edgeStyle },
      { id: "etel-plan", source: "ask-tel-gym", target: "ask-plan", animated: true, style: edgeStyle },
      { id: "eplan-ini", source: "ask-plan", target: "ask-inicio", animated: true, style: edgeStyle },
      { id: "eini-conf", source: "ask-inicio", target: "message-insc-conf", animated: true, style: edgeStyle },
      { id: "econg-y", source: "condition-congelar", sourceHandle: "yes", target: "message-congelar", animated: true, style: edgeStyle },
      { id: "econg-n", source: "condition-congelar", sourceHandle: "no", target: "message-ubicacion", animated: true, style: edgeStyle },
    ],
  },
];

export async function seedTemplates() {
  // Check if templates already exist
  const existing = await db
    .select()
    .from(botFlows)
    .where(eq(botFlows.isTemplate, true));

  if (existing.length > 0) return;

  for (const tmpl of templates) {
    await db.insert(botFlows).values({
      userId: SYSTEM_USER_ID,
      name: tmpl.name,
      description: tmpl.description,
      status: "active",
      isTemplate: true,
      nodes: tmpl.nodes,
      edges: tmpl.edges,
    });
  }

  console.log(`Seeded ${templates.length} bot flow templates`);
}
